version: 2.1
orbs:
  bun-orb: cmgriffing/bun-orb@0.0.29
  electron: electron/electron@3

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - bun-orb/setup
      - restore_cache:
          keys:
            - v1-bun-deps-{{ checksum "bun.lockb" }}
            - v1-bun-deps-
      - run: |
          bun install bun bake
      - save_cache:
          key: v1-bun-deps-{{ checksum "bun.lockb" }}
          paths:
            - ~/.bun/install/cache
            - node_modules

workflows:
  use-bun-orb:
    jobs:
      - build
