version: 2.1
orbs:
  bun-orb: cmgriffing/bun-orb@0.0.29

jobs:
  # build_windows:
  #   docker:
  #     - image: electronuserland/builder:wine
  #   steps:
  #     - checkout
  #     - run: bun i && bun run build:win

  build_macos:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - run: security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: security default-keychain -s build.keychain
      - run: security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
      - run: echo $KEYSTORE | base64 --decode - > keystore.p12
      - run: security import keystore.p12 -k build.keychain -P $KEYCHAIN_PASSWORD -T /usr/bin/codesign
      - run: bun i && bun run build:mac

workflows:
  version: 2
  build:
    jobs:
      # - build_windows
      - build_macos
