name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Snapcraft on Linux
        if: runner.os == 'Linux'
        run: sudo snap install snapcraft --classic

      - name: Install Dependencies
        env:
          BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun install --frozen-lockfile

      - name: Build/release Electron app
        run: bun run build:${{ runner.os }}
        env:
          GH_TOKEN: ${{ github.token }}

        # uses: samuelmeuli/action-electron-builder@v1
        # with:
        #   github_token: ${{ github.token }}
        #   release: ${{ startsWith(github.ref, 'refs/tags/v') }}
